services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: outdoor_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-outdoor_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-outdoor_pass}
      POSTGRES_DB: ${DB_NAME:-outdoor_rental}
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/docker/init-db:/docker-entrypoint-initdb.d
    networks:
      - outdoor_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-outdoor_user} -d ${DB_NAME:-outdoor_rental}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend Node.js
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: outdoor_backend
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${PORT:-3333}
      DATABASE_URL: postgresql://${DB_USER:-outdoor_user}:${DB_PASSWORD:-outdoor_pass}@postgres:5432/${DB_NAME:-outdoor_rental}
      JWT_SECRET: ${JWT_SECRET:-seu_jwt_secret_super_seguro_2024}
    ports:
      - "3333:3333"
    volumes:
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json
      - ./backend/package-lock.json:/app/package-lock.json
      - ./backend/server.js:/app/server.js
      - backend_node_modules:/app/node_modules
    networks:
      - outdoor_network
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "npm install && npm run dev"

  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: outdoor_frontend
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://localhost:3333/api
      REACT_APP_ENVIRONMENT: ${NODE_ENV:-development}
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
      - frontend_node_modules:/app/node_modules
    networks:
      - outdoor_network
    depends_on:
      - backend
    command: sh -c "npm install && npm run dev"

  # pgAdmin para gerenciamento do banco
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: outdoor_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@outdoor.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin123}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./backend/docker/pgadmin/servers.json:/pgadmin4/servers.json
    networks:
      - outdoor_network
    depends_on:
      postgres:
        condition: service_healthy

  # Redis para cache (opcional)
  redis:
    image: redis:7-alpine
    container_name: outdoor_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - outdoor_network
    command: redis-server --appendonly yes

  # Nginx para proxy e servir arquivos estáticos (produção)
  nginx:
    image: nginx:alpine
    container_name: outdoor_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - outdoor_network
    depends_on:
      - frontend
      - backend
    profiles:
      - production

networks:
  outdoor_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
  redis_data:
  backend_node_modules:
  frontend_node_modules: